export const userActions = {
  GET_LIST_USER: "GET_LIST_USER",
  GET_LIST_USER_SUCCESS: "GET_LIST_USER_SUCCESS",
  ADD_USER: "ADD_USER",
  UPDATE_USER_INFO: "UPDATE_USER_INFO",
  UPDATE_USER_PROFILE: "UPDATE_USER_PROFILE",
  GET_ME: "GET_ME",
  GET_ME_SUCCESS: "GET_ME_SUCCESS",
  GET_LIST_USER_ADMIN: "GET_LIST_USER_ADMIN",
  GET_LIST_USER_ADMIN_SUCCESS: "GET_LIST_USER_ADMIN_SUCCESS",
  DELETE_USER: "DELETE_USER",
  IMPORT_USER: "IMPORT_USER",
};

export const permissionActions = {
  ADD_PERMISSION: "ADD_PERMISSION",
  DELETE_PERMISSION: "DELETE_PERMISSION",
  GET_LIST_PERMISSION: "GET_LIST_PERMISSION",
  GET_LIST_PERMISSION_SUCCESS: "GET_LIST_PERMISSION_SUCCESS",
};

export const roomActions = {
  ADD_ROOM: "ADD_ROOM",
  UPDATE_ROOM: "UPDATE_ROOM",
  DELETE_ROOM: "DELETE_ROOM",
  GET_LIST_ROOM: "GET_LIST_ROOM",
  GET_LIST_ROOM_SUCCESS: "GET_LIST_ROOM_SUCCESS",
}