export const userActions = {
    GET_LIST_USER: "GET_LIST_USER",
    GET_LIST_USER_SUCCESS: "GET_LIST_USER_SUCCESS",
    ADD_USER: "ADD_USER",
    UPDATE_USER_INFO: "UPDATE_USER_INFO",
    UPDATE_USER_PROFILE: "UPDATE_USER_PROFILE",
    GET_ME: "GET_ME",
    GET_ME_SUCCESS: "GET_ME_SUCCESS",
    GET_LIST_USER_ADMIN: "GET_LIST_USER_ADMIN",
    GET_LIST_USER_ADMIN_SUCCESS: "GET_LIST_USER_ADMIN_SUCCESS",
}